#!/usr/bin/env bash

set -e

BRIGHTNESS_STEPS=25

case $1 in
up)
    brightnessctl --device='smc::kbd_backlight' set "${BRIGHTNESS_STEPS:-5}%+" -q
    ;;
down)
    brightnessctl --device='smc::kbd_backlight' set "${BRIGHTNESS_STEPS:-5}%-" -q
    ;;
esac
