#!/usr/bin/env bash

set -e

MIRRORLIST="/etc/pacman.d/mirrorlist"
TEMP_MIRRORLIST="/tmp/mirrorlist.tmp"
COUNTRIES="Germany,Russia,Netherlands"
PROTOCOL="https"
AGE="24"
SORT="rate"
LATEST="20"

sudo reflector --verbose --protocol $PROTOCOL --age $AGE --sort $SORT --latest $LATEST --country $COUNTRIES --save $TEMP_MIRRORLIST

: >$MIRRORLIST

while read -r line; do
    if [[ $line == http* ]]; then
        if curl --output /dev/null --silent --head --fail "$line"; then
            echo "$line" >>$MIRRORLIST
        fi
    fi
done <$TEMP_MIRRORLIST

rm $TEMP_MIRRORLIST
