#!/usr/bin/env bash

set -e

if pgrep -x "sing-box" >/dev/null; then
    echo "Stopping existing sing-box process..."
    sudo pkill sing-box
else
    echo "No existing sing-box process found."
fi

echo "Starting sing-box..."
sudo sing-box run -c ~/.dotfiles/personal/access.json
